### ISSUE TITLE
[iOS] GIFs not loading properly when in a listview.

### ISSUE THREAD

**Issue by christianjgreen** [AndreaVitale/av.imageview#16] opened 2017-02-08 15:22 UTC
We are having an issue on iOS were GIFs are not having the proper behavior. Often, they will not load until scrolled past and then back to multiple times. Working GIFs will also disappear when scrolled past and then back to.

**Comment by arifje** [comment] 2017-02-09 09:41
Same experience here. Only default views like webView, imageView, etc won't disappear from the listView after scrolling up and down. Third-party addons do vanish, won't come back/re-initialize.

**Comment by AndreaVitale** [comment] 2017-07-07 10:41
Hi all maybe is a ListView implementation problem that doesn't support in a simple way modules and widget as children of a childTemplate.

**Comment by m1ga** [comment] 2017-07-22 19:47
@Arthien @skoften could you test: https://github.com/AndreaVitale/imageview/pull/27 (binary in the post) to see if your problem is fixed?

**Comment by AndreaVitale** [comment] 2017-08-09 17:56
Updated the SDWebImage library to the latest one (4.1.0) and switched to `FLAnimatedImageView` that is declared to be lighter rendering GIF. Could you please try if the [latest version](https://github.com/AndreaVitale/imageview/releases/tag/iOS-1.1.0) fixes your problems?
I tested it with a sample app and no issues were found.

Closing the ticket. If the issue is not fixed for you, please reopen it.

**Closed as completed by AndreaVitale** 2017-08-09 17:56 UTC

**Comment by darknos** [comment] 2017-08-11 11:05
Thank you very much! I confirm that it works now. I dropped off my workaround and I'll release an app today. Great job!
